version: '3.8'

services:
  api:
    build: .
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app