version: '3.8'

services:
  api:
    container_name: events_api
    build:
      context: .
      args:
        - LOG_DIR
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - $LOG_DIR:$LOG_DIR