# Generated by Django 4.2.6 on 2023-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Registration Deadline"
            ),
        ),
    ]
