# Generated by Django 4.2.6 on 2023-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_event_registration_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="number_of_seats",
            field=models.IntegerField(default=0, verbose_name="Number of seats"),
        ),
    ]
